env:
  commonjs: false
  browser: true
  es2021: true
  jquery: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 12
rules:
  no-var: off
  guard-for-in: off
  no-trailing-spaces: off
  camelcase: off
  padded-blocks: off
  prefer-const: off
  max-len: off
  require-jsdoc: off
  valid-jsdoc: off
  no-multiple-empty-lines: off
  comma-dangle: off
  no-unused-vars: off
  no-useless-escape: off
  prefer-spread: off
  indent:
    - error
    - 4
